spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.62.221.163:3306/InsightNews
    username: dev
    password: '030530'
  redis:
    host: 116.62.221.163
    port: 6379
    database: 0
    password: '030530'
    timeout: 5000  # 设置为 5 秒
    lettuce:
      pool:
        max-active: 8  #最大连接
        max-idle: 8   #最大空闲连接
        min-idle: 0   #最小空闲连接
        max-wait: 100ms #连接等待时间










